server {
    listen 80;
    listen 443;
    server_name localhost;
    root "__PROJECT_PUBLIC_PATH__";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        fastcgi_index index.php;
        fastcgi_pass 127.0.0.1:__PHP_CGI_PORT__;
    }
}

server {
    listen __PHPMYADMIN_PORT__;
    server_name localhost;
    root "__PHPMYADMIN_ROOT_PATH__";
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
        fastcgi_pass 127.0.0.1:__PHP_CGI_PORT__;
    }
}
